/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hibernateteste.app;

import com.hibernateteste.app.util.HibernateUtil;

public class App {
    public static void main(String[] args) {

        HibernateUtil.shutdown();
    }
}
